import { BadgeCheck, CalendarCheck2, CircleCheck, ClipboardList, Plus, ScanLine, XCircle } from 'lucide-react';
import { useMemo, useState } from 'react';

import { GlassCard, MetricCard, PremiumButton, Stepper } from '@/components/design-system';
import { useToast } from '@/contexts/toast-context';
import type { BookingRecord, EventRecord } from '@/types/api';

import { DataState, EmptyResource, OperationsPage, ResourceCrudControls, ResourceDrawer, ResourceFormDialog, Status } from './operations-ui';
import { useResourceCollection } from './use-resource-collection';

export function BookingsPage() {
  const bookings = useResourceCollection<BookingRecord, { eventId: string; reference: string }, { eventId?: string; reference?: string }>('bookings');
  const events = useResourceCollection<EventRecord, { endsAt: string; name: string; startsAt: string }, { endsAt?: string; name?: string; startsAt?: string }>('events');
  const [createOpen, setCreateOpen] = useState(false);
  const [selected, setSelected] = useState<BookingRecord | null>(null);
  const { show } = useToast();
  const eventOptions = useMemo(() => (events.data ?? []).map((event) => ({ label: event.name, value: event.id })), [events.data]);
  const counts = useMemo(() => ({ completed: (bookings.data ?? []).filter((booking) => booking.status === 'COMPLETED').length, confirmed: (bookings.data ?? []).filter((booking) => booking.status === 'CONFIRMED').length, pending: (bookings.data ?? []).filter((booking) => booking.status === 'PENDING').length }), [bookings.data]);
  const action = (name: 'cancel' | 'check-in' | 'complete' | 'confirm') => { if (selected === null) return; bookings.workflow.mutate({ action: name, id: selected.id }, { onError: (error) => show(error instanceof Error ? error.message : 'Booking workflow could not be updated.'), onSuccess: () => show(`Booking ${name === 'check-in' ? 'checked in' : `${name}ed`}.`) }); };

  return <OperationsPage eyebrow="Enterprise reservation platform" icon={ClipboardList} title="Bookings" description="Track every reservation through a clear, verified confirmation and check-in workflow." action={<PremiumButton variant="secondary" onClick={() => setCreateOpen(true)}><Plus size={16} />New booking</PremiumButton>}>
    <DataState title="Bookings" isLoading={bookings.isLoading || events.isLoading} error={bookings.error ?? events.error} onRetry={() => { void bookings.refetch(); void events.refetch(); }}>
      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="Pending confirmation" value={String(counts.pending)} trend={{ positive: true, value: 'Queue monitored' }} /><MetricCard label="Confirmed" value={String(counts.confirmed)} trend={{ positive: true, value: 'Verified' }} /><MetricCard label="Completed" value={String(counts.completed)} trend={{ positive: true, value: 'Closed loop' }} /><GlassCard className="p-5"><p className="ss-kicker text-slate-400">Reservation integrity</p><p className="mt-3 text-lg font-semibold tracking-[-.03em]">Event-linked</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-300">Every booking must reference an existing event.</p></GlassCard></section>
      {(bookings.data?.length ?? 0) === 0 ? <EmptyResource icon={CalendarCheck2} title="No reservations in the workflow" description="Create a booking for a connected event to start the confirmation lifecycle." action={<PremiumButton variant="secondary" onClick={() => setCreateOpen(true)}><Plus size={16} />New booking</PremiumButton>} /> : <section className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]"><GlassCard className="overflow-hidden"><div className="border-b border-slate-200/80 p-5 dark:border-white/10"><p className="ss-kicker text-slate-400">Reservation ledger</p><h2 className="mt-1 text-xl font-semibold tracking-[-.03em]">Booking lifecycle queue</h2></div><div className="divide-y divide-slate-100 dark:divide-white/[.07]">{bookings.data?.map((booking) => <button type="button" key={booking.id} onClick={() => setSelected(booking)} className="group grid w-full gap-4 px-5 py-4 text-left transition hover:bg-cyan-50/50 dark:hover:bg-cyan-400/[.045] sm:grid-cols-[1fr_auto]"><span><span className="flex items-center gap-2 text-sm font-semibold"><span className="grid h-8 w-8 place-items-center rounded-lg bg-slate-950 text-white dark:bg-white dark:text-slate-950"><ClipboardList size={15} /></span>{booking.reference}</span><span className="mt-2 block text-xs text-slate-500 dark:text-slate-300">Event reference · {booking.eventId}</span></span><span className="flex items-center"><Status value={booking.status} /></span></button>)}</div></GlassCard><GlassCard className="p-5"><p className="ss-kicker text-slate-400">Workflow timeline</p><h2 className="mt-1 text-lg font-semibold tracking-[-.03em]">Reservation progression</h2><div className="mt-7"><Stepper activeStep={2} steps={['Pending', 'Confirmed', 'Check-in', 'Completed']} /></div><div className="mt-8 rounded-2xl border border-cyan-200/70 bg-cyan-50/60 p-4 dark:border-cyan-400/15 dark:bg-cyan-400/[.07]"><div className="flex gap-3"><BadgeCheck size={20} className="shrink-0 text-cyan-600 dark:text-cyan-300" /><p className="text-sm leading-6 text-cyan-900 dark:text-cyan-100">Open any booking to use only the operations that are valid for its current state.</p></div></div></GlassCard></section>}
    </DataState>
    <ResourceFormDialog fields={[{ label: 'Booking reference', name: 'reference', placeholder: 'e.g. BOOK-2026-0001', required: true }, { label: 'Event', name: 'eventId', options: eventOptions, required: true, type: 'select' }]} open={createOpen} onClose={() => setCreateOpen(false)} onSubmit={(values) => bookings.create.mutate({ eventId: values.eventId ?? '', reference: values.reference ?? '' }, { onError: (error) => show(error instanceof Error ? error.message : 'Booking could not be created.'), onSuccess: () => { setCreateOpen(false); show('Booking entered into the confirmation workflow.'); } })} submitting={bookings.create.isPending} title="Create booking" />
    <ResourceDrawer open={selected !== null} onClose={() => setSelected(null)} title={selected?.reference ?? 'Booking workflow'}>{selected !== null ? <div className="space-y-6"><div className="rounded-2xl bg-gradient-to-br from-sky-500 to-cyan-600 p-5 text-slate-950"><p className="ss-kicker opacity-65">Booking control</p><p className="mt-3 text-2xl font-semibold tracking-[-.04em]">{selected.reference}</p><p className="mt-2 text-sm opacity-75">Event ID · {selected.eventId}</p></div><Status value={selected.status} /><div className="grid gap-2">{selected.status === 'PENDING' ? <><PremiumButton loading={bookings.workflow.isPending} variant="success" onClick={() => action('confirm')}><CircleCheck size={16} />Confirm booking</PremiumButton><PremiumButton loading={bookings.workflow.isPending} variant="danger" onClick={() => action('cancel')}><XCircle size={16} />Cancel booking</PremiumButton></> : null}{selected.status === 'CONFIRMED' ? <><PremiumButton loading={bookings.workflow.isPending} variant="secondary" onClick={() => action('check-in')}><ScanLine size={16} />Check in</PremiumButton><PremiumButton loading={bookings.workflow.isPending} variant="danger" onClick={() => action('cancel')}>Cancel booking</PremiumButton></> : null}{selected.status === 'CHECKED_IN' ? <PremiumButton loading={bookings.workflow.isPending} variant="success" onClick={() => action('complete')}>Complete booking</PremiumButton> : null}</div><ResourceCrudControls fields={[{ label: 'Booking reference', name: 'reference', placeholder: 'e.g. BOOK-2026-0001', required: true }, { label: 'Event', name: 'eventId', options: eventOptions, required: true, type: 'select' }]} initialValues={{ eventId: selected.eventId, reference: selected.reference }} title="booking" updatePending={bookings.update.isPending} removePending={bookings.remove.isPending} onUpdate={(values) => bookings.update.mutate({ id: selected.id, input: { eventId: values.eventId ?? selected.eventId, reference: values.reference ?? selected.reference } }, { onError: (error) => show(error instanceof Error ? error.message : 'Booking could not be updated.'), onSuccess: () => show('Booking details updated.') })} onDelete={() => bookings.remove.mutate(selected.id, { onError: (error) => show(error instanceof Error ? error.message : 'Booking could not be deleted.'), onSuccess: () => { setSelected(null); show('Booking removed from the ledger.'); } })} deleteLabel="Delete booking" /></div> : null}</ResourceDrawer>
  </OperationsPage>;
}
