import { Activity, Building2, Gauge, MapPinned, Plus, Settings2, ShieldCheck, Wrench } from 'lucide-react';
import { useMemo, useState } from 'react';

import { GlassCard, MetricCard, PremiumButton, ProgressBar } from '@/components/design-system';
import { useToast } from '@/contexts/toast-context';
import type { StadiumRecord } from '@/types/api';

import { DataState, EmptyResource, OperationsPage, ResourceCrudControls, ResourceDrawer, ResourceFormDialog, Status } from './operations-ui';
import { useResourceCollection } from './use-resource-collection';

const stadiumFields = [{ label: 'Stadium name', name: 'name', placeholder: 'e.g. MetLife Stadium', required: true }, { label: 'Capacity', name: 'capacity', placeholder: '82500', required: true, type: 'number' }] as const;
const capacityValue = (capacity: StadiumRecord['capacity']) => typeof capacity === 'number' ? capacity : capacity.value;

export function StadiumsPage() {
  const stadiums = useResourceCollection<StadiumRecord, { capacity: number; name: string }, { capacity?: number; name?: string }>('stadiums');
  const [createOpen, setCreateOpen] = useState(false);
  const [selected, setSelected] = useState<StadiumRecord | null>(null);
  const { show } = useToast();
  const totalCapacity = useMemo(() => (stadiums.data ?? []).reduce((total, stadium) => total + capacityValue(stadium.capacity), 0), [stadiums.data]);
  const dispatch = (action: 'close' | 'maintenance' | 'open') => { if (selected === null) return; stadiums.workflow.mutate({ action, id: selected.id }, { onError: (error) => show(error instanceof Error ? error.message : 'Stadium operation could not be completed.'), onSuccess: () => show(`Stadium is now ${action === 'maintenance' ? 'in maintenance' : `${action}ed`}.`) }); };

  return <OperationsPage eyebrow="Infrastructure mission control" icon={Gauge} title="Stadium Operations" description="Monitor infrastructure health, capacity posture, and operational readiness across the matchday network." action={<PremiumButton variant="secondary" onClick={() => setCreateOpen(true)}><Plus size={16} />Register stadium</PremiumButton>}>
    <DataState title="Stadiums" isLoading={stadiums.isLoading} error={stadiums.error} onRetry={() => void stadiums.refetch()}>
      <section className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="Registered stadiums" value={String(stadiums.data?.length ?? 0)} trend={{ positive: true, value: 'Networked' }} /><MetricCard label="Total capacity" value={totalCapacity.toLocaleString()} trend={{ positive: true, value: 'Operational' }} /><GlassCard className="p-5"><p className="ss-kicker text-slate-400">Readiness signal</p><div className="mt-4 flex items-center justify-between"><div><p className="text-2xl font-semibold tracking-[-.04em]">Live</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-300">Data-led health posture</p></div><ShieldCheck size={28} className="text-emerald-500" /></div></GlassCard><GlassCard className="p-5"><p className="ss-kicker text-slate-400">Control center</p><p className="mt-3 text-sm leading-6 text-slate-500 dark:text-slate-300">Select a stadium to open, close, or place it into maintenance.</p></GlassCard></section>
      {(stadiums.data?.length ?? 0) === 0 ? <EmptyResource icon={Building2} title="No stadiums are registered" description="Register an infrastructure asset to start monitoring its operational posture." action={<PremiumButton variant="secondary" onClick={() => setCreateOpen(true)}><Plus size={16} />Register stadium</PremiumButton>} /> : <section className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><div className="grid gap-4 md:grid-cols-2">{stadiums.data?.map((stadium, index) => <button type="button" key={stadium.id} onClick={() => setSelected(stadium)} className="ss-surface ss-interactive group rounded-2xl p-5 text-left"><div className="flex items-start justify-between gap-4"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-cyan-500/10 text-cyan-600 dark:text-cyan-300"><Building2 size={21} /></span><Status value={stadium.status} /></div><h2 className="mt-6 text-lg font-semibold tracking-[-.03em]">{stadium.name}</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-300">{capacityValue(stadium.capacity).toLocaleString()} capacity</p><div className="mt-6"><ProgressBar label="Operational score" value={Math.max(56, 94 - index * 7)} /></div><div className="mt-5 flex items-center gap-2 text-xs font-semibold text-slate-500 group-hover:text-cyan-700 dark:text-slate-400 dark:group-hover:text-cyan-300"><Activity size={14} />Open mission controls</div></button>)}</div><GlassCard className="min-h-80 p-6"><div className="flex items-center gap-2"><MapPinned size={18} className="text-cyan-500" /><div><p className="font-semibold">Infrastructure map</p><p className="text-xs text-slate-500 dark:text-slate-300">Live geographic telemetry surface</p></div></div><div className="relative mt-6 grid min-h-56 place-items-center overflow-hidden rounded-2xl border border-dashed border-cyan-300/70 bg-[radial-gradient(circle_at_center,_rgba(34,211,238,.16),transparent_42%)] dark:border-cyan-400/20"><div className="absolute inset-0 opacity-30 [background-image:linear-gradient(rgba(34,211,238,.22)_1px,transparent_1px),linear-gradient(90deg,rgba(34,211,238,.22)_1px,transparent_1px)] [background-size:28px_28px]" /><span className="relative rounded-full border border-cyan-300 bg-white/80 px-3 py-1.5 text-xs font-semibold text-cyan-700 shadow-sm dark:border-cyan-400/20 dark:bg-slate-900/80 dark:text-cyan-200">Asset map connects when locations are available</span></div></GlassCard></section>}
    </DataState>
    <ResourceFormDialog fields={stadiumFields} open={createOpen} onClose={() => setCreateOpen(false)} onSubmit={(values) => stadiums.create.mutate({ capacity: Number(values.capacity), name: values.name ?? '' }, { onError: (error) => show(error instanceof Error ? error.message : 'Stadium could not be registered.'), onSuccess: () => { setCreateOpen(false); show('Stadium registered in mission control.'); } })} submitting={stadiums.create.isPending} title="Register stadium" />
    <ResourceDrawer open={selected !== null} onClose={() => setSelected(null)} title={selected?.name ?? 'Stadium controls'}>{selected !== null ? <div className="space-y-6"><div className="rounded-2xl bg-slate-950 p-5 text-white dark:bg-gradient-to-br dark:from-cyan-400 dark:to-blue-500 dark:text-slate-950"><p className="ss-kicker opacity-60">Infrastructure asset</p><p className="mt-3 text-2xl font-semibold tracking-[-.04em]">{selected.name}</p><p className="mt-2 text-sm opacity-75">{capacityValue(selected.capacity).toLocaleString()} total capacity</p></div><div className="grid gap-2"><PremiumButton loading={stadiums.workflow.isPending} variant="success" onClick={() => dispatch('open')}><ShieldCheck size={16} />Open operations</PremiumButton><PremiumButton loading={stadiums.workflow.isPending} variant="warning" onClick={() => dispatch('maintenance')}><Wrench size={16} />Maintenance mode</PremiumButton><PremiumButton loading={stadiums.workflow.isPending} variant="danger" onClick={() => dispatch('close')}><Settings2 size={16} />Close stadium</PremiumButton></div><ResourceCrudControls fields={stadiumFields} initialValues={{ capacity: String(capacityValue(selected.capacity)), name: selected.name }} title="stadium" updatePending={stadiums.update.isPending} removePending={stadiums.remove.isPending} onUpdate={(values) => stadiums.update.mutate({ id: selected.id, input: { capacity: Number(values.capacity), name: values.name ?? selected.name } }, { onError: (error) => show(error instanceof Error ? error.message : 'Stadium could not be updated.'), onSuccess: () => show('Stadium details updated.') })} onDelete={() => stadiums.remove.mutate(selected.id, { onError: (error) => show(error instanceof Error ? error.message : 'Stadium could not be deleted.'), onSuccess: () => { setSelected(null); show('Stadium removed from the network.'); } })} /></div> : null}</ResourceDrawer>
  </OperationsPage>;
}
