import { CalendarClock, Flag, Plus, Shield, UsersRound } from 'lucide-react';
import { useMemo, useState } from 'react';

import { GlassCard, MetricCard, PremiumButton } from '@/components/design-system';
import { useToast } from '@/contexts/toast-context';
import type { SportRecord, TeamRecord } from '@/types/api';

import { DataState, EmptyResource, OperationsPage, ResourceCrudControls, ResourceDrawer, ResourceFormDialog } from './operations-ui';
import { useResourceCollection } from './use-resource-collection';

export function TeamsPage() {
  const teams = useResourceCollection<TeamRecord, { name: string; sportId: string; sportName: string }, { name?: string; sportId?: string; sportName?: string }>('teams');
  const sports = useResourceCollection<SportRecord, { name: string }, { name?: string }>('sports');
  const [createOpen, setCreateOpen] = useState(false);
  const [selected, setSelected] = useState<TeamRecord | null>(null);
  const { show } = useToast();
  const sportOptions = useMemo(() => (sports.data ?? []).map((sport) => ({ label: sport.name, value: sport.id })), [sports.data]);
  const submit = (values: Record<string, string>) => { const sport = sports.data?.find((item) => item.id === values.sportId); if (sport === undefined) { show('Select a sport from the connected catalogue.'); return; } teams.create.mutate({ name: values.name ?? '', sportId: sport.id, sportName: sport.name }, { onError: (error) => show(error instanceof Error ? error.message : 'Team could not be created.'), onSuccess: () => { setCreateOpen(false); show('Team added to operations.'); } }); };

  return <OperationsPage eyebrow="Team operations" icon={UsersRound} title="Teams" description="Bring every competition team into one operational roster with sport context and event-ready visibility." action={<PremiumButton variant="secondary" onClick={() => setCreateOpen(true)}><Plus size={16} />Add team</PremiumButton>}>
    <DataState title="Teams" isLoading={teams.isLoading || sports.isLoading} error={teams.error ?? sports.error} onRetry={() => { void teams.refetch(); void sports.refetch(); }}>
      <section className="grid gap-4 md:grid-cols-3"><MetricCard label="Active teams" value={String(teams.data?.length ?? 0)} trend={{ positive: true, value: 'Rostered' }} /><MetricCard label="Sports represented" value={String(new Set((teams.data ?? []).map((team) => team.sport.name)).size)} trend={{ positive: true, value: 'Connected' }} /><GlassCard className="p-5"><p className="ss-kicker text-slate-400">Roster posture</p><p className="mt-3 text-lg font-semibold tracking-[-.03em]">Event-ready</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-300">Teams retain a direct, verified relationship to their sport.</p></GlassCard></section>
      {(teams.data?.length ?? 0) === 0 ? <EmptyResource icon={Shield} title="The team roster is empty" description="Add a team after connecting at least one sport in the competition catalogue." action={<PremiumButton variant="secondary" onClick={() => setCreateOpen(true)}><Plus size={16} />Add team</PremiumButton>} /> : <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{teams.data?.map((team, index) => <button type="button" key={team.id} onClick={() => setSelected(team)} className="ss-surface ss-interactive group rounded-2xl p-5 text-left"><div className="flex items-start justify-between"><span className="grid h-12 w-12 place-items-center rounded-full bg-gradient-to-br from-slate-900 to-slate-700 text-sm font-bold text-white dark:from-violet-400 dark:to-indigo-500 dark:text-slate-950">{team.name.slice(0, 2).toUpperCase()}</span><Flag size={18} className="text-slate-400 group-hover:text-cyan-500" /></div><h2 className="mt-6 text-lg font-semibold tracking-[-.03em]">{team.name}</h2><p className="mt-1 text-sm text-cyan-700 dark:text-cyan-300">{team.sport.name}</p><div className="mt-5 flex items-center gap-2 border-t border-slate-200/70 pt-4 text-xs text-slate-500 dark:border-white/10 dark:text-slate-300"><CalendarClock size={14} />Upcoming event visibility · Slot {index + 1}</div></button>)}</section>}
    </DataState>
    <ResourceFormDialog fields={[{ label: 'Team name', name: 'name', placeholder: 'e.g. Northstar FC', required: true }, { label: 'Sport', name: 'sportId', options: sportOptions, required: true, type: 'select' }]} open={createOpen} onClose={() => setCreateOpen(false)} onSubmit={submit} submitting={teams.create.isPending} title="Add team" />
    <ResourceDrawer open={selected !== null} onClose={() => setSelected(null)} title={selected?.name ?? 'Team operations'}>{selected !== null ? <div className="space-y-6"><div className="rounded-2xl bg-slate-950 p-5 text-white dark:bg-gradient-to-br dark:from-violet-400 dark:to-indigo-500 dark:text-slate-950"><p className="ss-kicker opacity-65">Competition roster</p><p className="mt-3 text-2xl font-semibold tracking-[-.04em]">{selected.name}</p><p className="mt-2 text-sm opacity-75">{selected.sport.name}</p></div><ResourceCrudControls fields={[{ label: 'Team name', name: 'name', placeholder: 'e.g. Northstar FC', required: true }, { label: 'Sport', name: 'sportId', options: sportOptions, required: true, type: 'select' }]} initialValues={{ name: selected.name, sportId: selected.sport.id }} title="team" updatePending={teams.update.isPending} removePending={teams.remove.isPending} onUpdate={(values) => { const sport = sports.data?.find((item) => item.id === values.sportId); if (sport === undefined) { show('Select a sport from the connected catalogue.'); return; } teams.update.mutate({ id: selected.id, input: { name: values.name ?? selected.name, sportId: sport.id, sportName: sport.name } }, { onError: (error) => show(error instanceof Error ? error.message : 'Team could not be updated.'), onSuccess: () => show('Team roster entry updated.') }); }} onDelete={() => teams.remove.mutate(selected.id, { onError: (error) => show(error instanceof Error ? error.message : 'Team could not be deleted.'), onSuccess: () => { setSelected(null); show('Team removed from operations.'); } })} deleteLabel="Remove team" /></div> : null}</ResourceDrawer>
  </OperationsPage>;
}
