import { CalendarClock, CalendarDays, MapPin, Plus, TimerReset } from 'lucide-react';
import { useMemo, useState } from 'react';

import { GlassCard, MetricCard, PremiumButton } from '@/components/design-system';
import { useToast } from '@/contexts/toast-context';
import type { VenueRecord } from '@/types/api';

import { DataState, EmptyResource, OperationsPage, ResourceCrudControls, ResourceDrawer, ResourceFormDialog, Status, formatDateTime } from './operations-ui';
import { useResourceCollection } from './use-resource-collection';

const venueFields = [{ label: 'Venue name', name: 'name', placeholder: 'e.g. Fan Zone East', required: true }, { label: 'Latitude', name: 'latitude', placeholder: '40.7128', required: true, type: 'number' }, { label: 'Longitude', name: 'longitude', placeholder: '-74.0060', required: true, type: 'number' }, { label: 'Address', name: 'addressLine1', placeholder: '1 Stadium Way' }, { label: 'City', name: 'city', placeholder: 'New York' }, { label: 'Country', name: 'country', placeholder: 'United States' }] as const;
const locationLabel = (venue: VenueRecord) => { const address = venue.location.address; return [address?.city, address?.country].filter(Boolean).join(', ') || 'Coordinates pending'; };
const coordinatesFor = (venue: VenueRecord) => ({ latitude: venue.location.coordinates?.latitude ?? venue.location.latitude ?? 0, longitude: venue.location.coordinates?.longitude ?? venue.location.longitude ?? 0 });

export function VenuesPage() {
  const venues = useResourceCollection<VenueRecord, { addressLine1?: string; city?: string; country?: string; latitude: number; longitude: number; name: string }, { latitude?: number; longitude?: number; name?: string }>('venues');
  const [createOpen, setCreateOpen] = useState(false);
  const [reserveOpen, setReserveOpen] = useState(false);
  const [selected, setSelected] = useState<VenueRecord | null>(null);
  const { show } = useToast();
  const reserved = useMemo(() => (venues.data ?? []).filter((venue) => venue.status === 'RESERVED').length, [venues.data]);
  const release = () => { if (selected === null) return; venues.workflow.mutate({ action: 'release', id: selected.id }, { onError: (error) => show(error instanceof Error ? error.message : 'Venue could not be released.'), onSuccess: () => show('Venue released to the availability grid.') }); };
  const reserve = (values: Record<string, string>) => { if (selected === null) return; venues.workflow.mutate({ action: 'reserve', id: selected.id, input: { endsAt: new Date(values.endsAt ?? '').toISOString(), startsAt: new Date(values.startsAt ?? '').toISOString() } }, { onError: (error) => show(error instanceof Error ? error.message : 'Venue could not be reserved.'), onSuccess: () => { setReserveOpen(false); show('Venue reservation added to the timeline.'); } }); };

  return <OperationsPage eyebrow="Facility reservation platform" icon={CalendarDays} title="Venue Operations" description="Manage availability, reservations, and facility readiness through an operational calendar built for matchday decisions." action={<PremiumButton variant="secondary" onClick={() => setCreateOpen(true)}><Plus size={16} />Add venue</PremiumButton>}>
    <DataState title="Venues" isLoading={venues.isLoading} error={venues.error} onRetry={() => void venues.refetch()}>
      <section className="grid gap-4 md:grid-cols-3"><MetricCard label="Venue inventory" value={String(venues.data?.length ?? 0)} trend={{ positive: true, value: 'Connected' }} /><MetricCard label="Active reservations" value={String(reserved)} trend={{ positive: reserved === 0, value: reserved === 0 ? 'Clear' : 'In progress' }} /><GlassCard className="p-5"><p className="ss-kicker text-slate-400">Reservation rule</p><p className="mt-3 text-lg font-semibold tracking-[-.03em]">Conflict-aware</p><p className="mt-1 text-sm leading-6 text-slate-500 dark:text-slate-300">Reserve an available venue with an explicit operational window.</p></GlassCard></section>
      {(venues.data?.length ?? 0) === 0 ? <EmptyResource icon={MapPin} title="No facilities are on the map" description="Add a venue to create an availability and reservation timeline." action={<PremiumButton variant="secondary" onClick={() => setCreateOpen(true)}><Plus size={16} />Add venue</PremiumButton>} /> : <section className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><GlassCard className="p-5"><div className="flex items-center gap-2"><CalendarClock size={18} className="text-cyan-500" /><div><p className="font-semibold">Availability timeline</p><p className="text-xs text-slate-500 dark:text-slate-300">Facility readiness in the current workspace</p></div></div><div className="mt-6 space-y-4">{venues.data?.map((venue) => <button type="button" key={venue.id} onClick={() => setSelected(venue)} className="group flex w-full items-center gap-3 rounded-xl p-2 text-left transition hover:bg-cyan-50/60 dark:hover:bg-cyan-400/[.05]"><span className={`h-10 w-1.5 rounded-full ${venue.status === 'RESERVED' ? 'bg-amber-400' : venue.status === 'AVAILABLE' ? 'bg-emerald-400' : 'bg-rose-400'}`} /><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{venue.name}</span><span className="mt-1 block text-xs text-slate-500 dark:text-slate-300">{venue.reservationTimeSlot === undefined ? 'No current reservation' : `${formatDateTime(venue.reservationTimeSlot.startsAt)} · ${formatDateTime(venue.reservationTimeSlot.endsAt)}`}</span></span><Status value={venue.status} /></button>)}</div></GlassCard><div className="grid gap-4 sm:grid-cols-2">{venues.data?.map((venue) => <button type="button" key={venue.id} onClick={() => setSelected(venue)} className="ss-surface ss-interactive group rounded-2xl p-5 text-left"><div className="flex items-start justify-between"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-violet-500/10 text-violet-600 dark:text-violet-300"><MapPin size={20} /></span><Status value={venue.status} /></div><h2 className="mt-5 text-lg font-semibold tracking-[-.03em]">{venue.name}</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-300">{locationLabel(venue)}</p><div className="mt-5 rounded-xl border border-slate-200/80 bg-white/55 p-3 text-xs text-slate-500 dark:border-white/10 dark:bg-white/[.04] dark:text-slate-300"><span className="flex items-center gap-2"><TimerReset size={14} className="text-cyan-500" />{venue.reservationTimeSlot === undefined ? 'Available for the next operation' : 'Reservation window in progress'}</span></div></button>)}</div></section>}
    </DataState>
    <ResourceFormDialog fields={venueFields} open={createOpen} onClose={() => setCreateOpen(false)} onSubmit={(values) => venues.create.mutate({ ...(values.addressLine1 ? { addressLine1: values.addressLine1 } : {}), ...(values.city ? { city: values.city } : {}), ...(values.country ? { country: values.country } : {}), latitude: Number(values.latitude), longitude: Number(values.longitude), name: values.name ?? '' }, { onError: (error) => show(error instanceof Error ? error.message : 'Venue could not be added.'), onSuccess: () => { setCreateOpen(false); show('Venue added to the facility network.'); } })} submitting={venues.create.isPending} title="Add venue" />
    <ResourceFormDialog fields={[{ label: 'Reservation starts', name: 'startsAt', required: true, type: 'datetime-local' }, { label: 'Reservation ends', name: 'endsAt', required: true, type: 'datetime-local' }]} open={reserveOpen} onClose={() => setReserveOpen(false)} onSubmit={reserve} submitting={venues.workflow.isPending} submitLabel="Reserve venue" title={`Reserve ${selected?.name ?? 'venue'}`} />
    <ResourceDrawer open={selected !== null} onClose={() => setSelected(null)} title={selected?.name ?? 'Venue reservation'}>{selected !== null ? <div className="space-y-6"><div className="rounded-2xl bg-gradient-to-br from-violet-600 to-indigo-700 p-5 text-white"><p className="ss-kicker opacity-70">Facility reservation</p><p className="mt-3 text-2xl font-semibold tracking-[-.04em]">{selected.name}</p><p className="mt-2 text-sm opacity-80">{locationLabel(selected)}</p></div><Status value={selected.status} /><div className="grid gap-2">{selected.status === 'RESERVED' ? <PremiumButton loading={venues.workflow.isPending} variant="success" onClick={release}>Release venue</PremiumButton> : <PremiumButton variant="secondary" onClick={() => setReserveOpen(true)}>Reserve time slot</PremiumButton>}<PremiumButton loading={venues.workflow.isPending} variant="warning" onClick={() => venues.workflow.mutate({ action: 'maintenance', id: selected.id }, { onError: (error) => show(error instanceof Error ? error.message : 'Venue maintenance could not start.'), onSuccess: () => show('Venue placed into maintenance.') })}>Maintenance mode</PremiumButton></div><ResourceCrudControls fields={venueFields.slice(0, 3)} initialValues={{ latitude: String(coordinatesFor(selected).latitude), longitude: String(coordinatesFor(selected).longitude), name: selected.name }} title="venue" updatePending={venues.update.isPending} removePending={venues.remove.isPending} onUpdate={(values) => venues.update.mutate({ id: selected.id, input: { latitude: Number(values.latitude), longitude: Number(values.longitude), name: values.name ?? selected.name } }, { onError: (error) => show(error instanceof Error ? error.message : 'Venue could not be updated.'), onSuccess: () => show('Venue details updated.') })} onDelete={() => venues.remove.mutate(selected.id, { onError: (error) => show(error instanceof Error ? error.message : 'Venue could not be deleted.'), onSuccess: () => { setSelected(null); show('Venue removed from the network.'); } })} /></div> : null}</ResourceDrawer>
  </OperationsPage>;
}
