import { ChevronDown } from 'lucide-react';
import { useState } from 'react';
import type { ReactNode } from 'react';

import { cn } from '@/lib/cn';

export function PageHeader({ action, description, title }: { action?: ReactNode; description: string; title: string }) { return <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-cyan-600 dark:text-cyan-300">StadiumSphere AI</p><h1 className="mt-2 text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600 dark:text-slate-300">{description}</p></div>{action}</header>; }
export function SectionHeader({ action, description, title }: { action?: ReactNode; description?: string; title: string }) { return <header className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">{title}</h2>{description ? <p className="mt-1 text-sm text-slate-500 dark:text-slate-300">{description}</p> : null}</div>{action}</header>; }
export function Breadcrumbs({ items }: { items: readonly string[] }) { return <nav aria-label="Breadcrumb" className="flex flex-wrap gap-2 text-xs text-slate-500 dark:text-slate-400">{items.map((item, index) => <span key={`${item}-${index}`} className="inline-flex items-center gap-2"><span>{item}</span>{index < items.length - 1 ? <span aria-hidden="true">/</span> : null}</span>)}</nav>; }
export function SegmentedControl({ options, value, onChange }: { onChange(value: string): void; options: readonly string[]; value: string }) { return <div role="tablist" className="inline-flex rounded-xl bg-slate-100 p-1 dark:bg-white/10">{options.map((option) => <button key={option} type="button" role="tab" aria-selected={value === option} onClick={() => onChange(option)} className={cn('focus-ring rounded-lg px-3 py-1.5 text-sm transition', value === option ? 'bg-white font-semibold shadow-sm dark:bg-slate-800' : 'text-slate-500 hover:text-slate-900 dark:text-slate-400 dark:hover:text-white')}>{option}</button>)}</div>; }
export function Accordion({ children, title }: { children: ReactNode; title: string }) { const [open, setOpen] = useState(false); return <section className="rounded-xl border border-slate-200 dark:border-white/10"><button type="button" onClick={() => setOpen((value) => !value)} aria-expanded={open} className="focus-ring flex w-full items-center justify-between px-4 py-3 text-left text-sm font-semibold">{title}<ChevronDown size={16} className={open ? 'rotate-180' : ''} /></button>{open ? <div className="border-t border-slate-200 px-4 py-3 text-sm text-slate-600 dark:border-white/10 dark:text-slate-300">{children}</div> : null}</section>; }
export function Timeline({ items }: { items: readonly { detail: string; title: string }[] }) { return <ol className="space-y-5">{items.map((item) => <li key={item.title} className="relative pl-6"><span className="absolute left-0 top-1.5 h-2.5 w-2.5 rounded-full bg-cyan-500 ring-4 ring-cyan-500/10" /><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-sm text-slate-500 dark:text-slate-300">{item.detail}</p></li>)}</ol>; }
export function Stepper({ activeStep, steps }: { activeStep: number; steps: readonly string[] }) { return <ol className="flex flex-wrap gap-3">{steps.map((step, index) => <li key={step} className={cn('inline-flex items-center gap-2 text-sm', index <= activeStep ? 'text-cyan-700 dark:text-cyan-300' : 'text-slate-400')}><span className={cn('grid h-6 w-6 place-items-center rounded-full text-xs font-semibold', index <= activeStep ? 'bg-cyan-500 text-slate-950' : 'bg-slate-100 dark:bg-white/10')}>{index + 1}</span>{step}</li>)}</ol>; }
export const Tabs = SegmentedControl;
