packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@scarf/scarf': false
  bcrypt: true
  esbuild: true
  unrs-resolver: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@swc/core'
  - esbuild
