import { z } from 'zod';
declare const environmentSchema: z.ZodObject<{
    NODE_ENV: z.ZodEnum<["development", "qa", "staging", "production", "test"]>;
    PORT: z.ZodNumber;
    API_PREFIX: z.ZodString;
    LOG_LEVEL: z.ZodEnum<["debug", "info", "warn", "error"]>;
    CORS_ORIGIN: z.ZodString;
    MONGODB_URI: z.ZodString;
    MONGODB_DATABASE: z.ZodString;
    MONGODB_SERVER_SELECTION_TIMEOUT_MS: z.ZodNumber;
    REDIS_HOST: z.ZodString;
    REDIS_PORT: z.ZodNumber;
    REDIS_PASSWORD: z.ZodOptional<z.ZodString>;
    RATE_LIMIT_TTL_MS: z.ZodNumber;
    RATE_LIMIT_MAX: z.ZodNumber;
    JWT_ACCESS_SECRET: z.ZodString;
    JWT_ACCESS_EXPIRES_IN: z.ZodNumber;
    JWT_REFRESH_SECRET: z.ZodString;
    JWT_REFRESH_EXPIRES_IN: z.ZodNumber;
    BCRYPT_SALT_ROUNDS: z.ZodNumber;
    SWAGGER_ENABLED: z.ZodEffects<z.ZodEnum<["true", "false"]>, boolean, "true" | "false">;
}, "strip", z.ZodTypeAny, {
    NODE_ENV: "development" | "qa" | "staging" | "production" | "test";
    PORT: number;
    API_PREFIX: string;
    LOG_LEVEL: "debug" | "info" | "warn" | "error";
    CORS_ORIGIN: string;
    MONGODB_URI: string;
    MONGODB_DATABASE: string;
    MONGODB_SERVER_SELECTION_TIMEOUT_MS: number;
    REDIS_HOST: string;
    REDIS_PORT: number;
    RATE_LIMIT_TTL_MS: number;
    RATE_LIMIT_MAX: number;
    JWT_ACCESS_SECRET: string;
    JWT_ACCESS_EXPIRES_IN: number;
    JWT_REFRESH_SECRET: string;
    JWT_REFRESH_EXPIRES_IN: number;
    BCRYPT_SALT_ROUNDS: number;
    SWAGGER_ENABLED: boolean;
    REDIS_PASSWORD?: string | undefined;
}, {
    NODE_ENV: "development" | "qa" | "staging" | "production" | "test";
    PORT: number;
    API_PREFIX: string;
    LOG_LEVEL: "debug" | "info" | "warn" | "error";
    CORS_ORIGIN: string;
    MONGODB_URI: string;
    MONGODB_DATABASE: string;
    MONGODB_SERVER_SELECTION_TIMEOUT_MS: number;
    REDIS_HOST: string;
    REDIS_PORT: number;
    RATE_LIMIT_TTL_MS: number;
    RATE_LIMIT_MAX: number;
    JWT_ACCESS_SECRET: string;
    JWT_ACCESS_EXPIRES_IN: number;
    JWT_REFRESH_SECRET: string;
    JWT_REFRESH_EXPIRES_IN: number;
    BCRYPT_SALT_ROUNDS: number;
    SWAGGER_ENABLED: "true" | "false";
    REDIS_PASSWORD?: string | undefined;
}>;
export type ApiEnvironment = z.infer<typeof environmentSchema>;
export declare function validateEnvironment(environment: Record<string, unknown>): ApiEnvironment;
export {};
