Object.assign(process.env, {
  API_PREFIX: 'api/v1',
  CORS_ORIGIN: 'http://localhost:5173',
  LOG_LEVEL: 'error',
  MONGODB_DATABASE: 'stadiumsphere',
  MONGODB_URI: 'mongodb://localhost:27017',
  MONGODB_SERVER_SELECTION_TIMEOUT_MS: '100',
  NODE_ENV: 'test',
  PORT: '3000',
  RATE_LIMIT_MAX: '100',
  RATE_LIMIT_TTL_MS: '60000',
  REDIS_HOST: 'localhost',
  REDIS_PORT: '6379',
  SWAGGER_ENABLED: 'false',
});
